# copy to serverless.yml and fill configs
service: afterwork-alert-feed-parsing

provider:
  name: aws
  profile: {{profile}}
  runtime: nodejs6.10
  region: eu-west-1

package:
  include:
    - untappdFeedParser.js
    - node_modules/**
  exclude:
    - *

functions:
  feedParsing:
    handler: untappdFeedParser.handler
    environment:
      FALLBACK_CHANNEL: '#fallback_if_some_city_doesnt_have_own_channel'
      # CHANNEL_TAMPERE: '#channel_for_this_city'
      # CHANNEL_JYVASKYLA: '#channel_for_this_city'
      # CHANNEL_HELSINKI: '#channel_for_this_city'
      # SLACK_WEBHOOK: {{webhook address}}
      AFTERWORK_TIME_SEQUENCE: 20
      # BOTNAME: Botname
      # UNTAPPD_ACCESS_TOKEN: {{insert token}}

    events:
      - schedule: rate(10 minutes)
