service: afterwork-alert-feed

provider:
  name: aws
  profile: ${env:AFTWRK_PROFILE}
  runtime: nodejs6.10
  region: eu-west-1
  memory: 128

package:
  include:
    - untappdFeedParser.js
    - node_modules/**
  exclude:
    - ./**

functions:
  # Parses Untappd feed and notifies to channels
  untappd:
    handler: untappdFeedParser.handler
    environment:
      # City to channel mappings are done in runtime by possible environment variables
      # Etc city called Lahti would search environment variable CHANNEL_LAHTI
      # Add these as many as you want or rely on fallback channel
      CHANNEL_TAMPERE: '#afterwork-tampere'
      CHANNEL_JYVASKYLA: '#afterwork-jkl'
      CHANNEL_HELSINKI: '#afterwork-helsinki'
      # If no channel for some city, use this
      FALLBACK_CHANNEL: ${env:AFTWRK_FALLBACK_CHANNEL}
      SLACK_WEBHOOK: ${env:AFTWRK_SLACK_WEBHOOK}
      BOTNAME: ${env:AFTWRK_BOTNAME}
      UNTAPPD_ACCESS_TOKEN: ${env:AFTWRK_UNTAPPD_ACCESS_TOKEN}
      AFTERWORK_TIME_SEQUENCE: 20

    events:
      - schedule: rate(10 minutes)

